// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/api.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/scalebox/scalebox-sdk-golang/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilesystemName is the fully-qualified name of the Filesystem service.
	FilesystemName = "sandboxagent.Filesystem"
	// ProcessName is the fully-qualified name of the Process service.
	ProcessName = "sandboxagent.Process"
	// ExecutionServiceName is the fully-qualified name of the ExecutionService service.
	ExecutionServiceName = "sandboxagent.ExecutionService"
	// ContextServiceName is the fully-qualified name of the ContextService service.
	ContextServiceName = "sandboxagent.ContextService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilesystemStatProcedure is the fully-qualified name of the Filesystem's Stat RPC.
	FilesystemStatProcedure = "/sandboxagent.Filesystem/Stat"
	// FilesystemMakeDirProcedure is the fully-qualified name of the Filesystem's MakeDir RPC.
	FilesystemMakeDirProcedure = "/sandboxagent.Filesystem/MakeDir"
	// FilesystemMoveProcedure is the fully-qualified name of the Filesystem's Move RPC.
	FilesystemMoveProcedure = "/sandboxagent.Filesystem/Move"
	// FilesystemListDirProcedure is the fully-qualified name of the Filesystem's ListDir RPC.
	FilesystemListDirProcedure = "/sandboxagent.Filesystem/ListDir"
	// FilesystemRemoveProcedure is the fully-qualified name of the Filesystem's Remove RPC.
	FilesystemRemoveProcedure = "/sandboxagent.Filesystem/Remove"
	// FilesystemWatchDirProcedure is the fully-qualified name of the Filesystem's WatchDir RPC.
	FilesystemWatchDirProcedure = "/sandboxagent.Filesystem/WatchDir"
	// FilesystemCreateWatcherProcedure is the fully-qualified name of the Filesystem's CreateWatcher
	// RPC.
	FilesystemCreateWatcherProcedure = "/sandboxagent.Filesystem/CreateWatcher"
	// FilesystemGetWatcherEventsProcedure is the fully-qualified name of the Filesystem's
	// GetWatcherEvents RPC.
	FilesystemGetWatcherEventsProcedure = "/sandboxagent.Filesystem/GetWatcherEvents"
	// FilesystemRemoveWatcherProcedure is the fully-qualified name of the Filesystem's RemoveWatcher
	// RPC.
	FilesystemRemoveWatcherProcedure = "/sandboxagent.Filesystem/RemoveWatcher"
	// ProcessListProcedure is the fully-qualified name of the Process's List RPC.
	ProcessListProcedure = "/sandboxagent.Process/List"
	// ProcessConnectProcedure is the fully-qualified name of the Process's Connect RPC.
	ProcessConnectProcedure = "/sandboxagent.Process/Connect"
	// ProcessStartProcedure is the fully-qualified name of the Process's Start RPC.
	ProcessStartProcedure = "/sandboxagent.Process/Start"
	// ProcessUpdateProcedure is the fully-qualified name of the Process's Update RPC.
	ProcessUpdateProcedure = "/sandboxagent.Process/Update"
	// ProcessStreamInputProcedure is the fully-qualified name of the Process's StreamInput RPC.
	ProcessStreamInputProcedure = "/sandboxagent.Process/StreamInput"
	// ProcessSendInputProcedure is the fully-qualified name of the Process's SendInput RPC.
	ProcessSendInputProcedure = "/sandboxagent.Process/SendInput"
	// ProcessSendSignalProcedure is the fully-qualified name of the Process's SendSignal RPC.
	ProcessSendSignalProcedure = "/sandboxagent.Process/SendSignal"
	// ExecutionServiceExecuteProcedure is the fully-qualified name of the ExecutionService's Execute
	// RPC.
	ExecutionServiceExecuteProcedure = "/sandboxagent.ExecutionService/Execute"
	// ContextServiceCreateContextProcedure is the fully-qualified name of the ContextService's
	// CreateContext RPC.
	ContextServiceCreateContextProcedure = "/sandboxagent.ContextService/CreateContext"
	// ContextServiceDestroyContextProcedure is the fully-qualified name of the ContextService's
	// DestroyContext RPC.
	ContextServiceDestroyContextProcedure = "/sandboxagent.ContextService/DestroyContext"
)

// FilesystemClient is a client for the sandboxagent.Filesystem service.
type FilesystemClient interface {
	Stat(context.Context, *connect.Request[pb.StatRequest]) (*connect.Response[pb.StatResponse], error)
	MakeDir(context.Context, *connect.Request[pb.MakeDirRequest]) (*connect.Response[pb.MakeDirResponse], error)
	Move(context.Context, *connect.Request[pb.MoveRequest]) (*connect.Response[pb.MoveResponse], error)
	ListDir(context.Context, *connect.Request[pb.ListDirRequest]) (*connect.Response[pb.ListDirResponse], error)
	Remove(context.Context, *connect.Request[pb.RemoveRequest]) (*connect.Response[pb.RemoveResponse], error)
	WatchDir(context.Context, *connect.Request[pb.WatchDirRequest]) (*connect.ServerStreamForClient[pb.WatchDirResponse], error)
	// Non-streaming versions of WatchDir
	CreateWatcher(context.Context, *connect.Request[pb.CreateWatcherRequest]) (*connect.Response[pb.CreateWatcherResponse], error)
	GetWatcherEvents(context.Context, *connect.Request[pb.GetWatcherEventsRequest]) (*connect.Response[pb.GetWatcherEventsResponse], error)
	RemoveWatcher(context.Context, *connect.Request[pb.RemoveWatcherRequest]) (*connect.Response[pb.RemoveWatcherResponse], error)
}

// NewFilesystemClient constructs a client for the sandboxagent.Filesystem service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilesystemClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilesystemClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filesystemMethods := pb.File_proto_api_proto.Services().ByName("Filesystem").Methods()
	return &filesystemClient{
		stat: connect.NewClient[pb.StatRequest, pb.StatResponse](
			httpClient,
			baseURL+FilesystemStatProcedure,
			connect.WithSchema(filesystemMethods.ByName("Stat")),
			connect.WithClientOptions(opts...),
		),
		makeDir: connect.NewClient[pb.MakeDirRequest, pb.MakeDirResponse](
			httpClient,
			baseURL+FilesystemMakeDirProcedure,
			connect.WithSchema(filesystemMethods.ByName("MakeDir")),
			connect.WithClientOptions(opts...),
		),
		move: connect.NewClient[pb.MoveRequest, pb.MoveResponse](
			httpClient,
			baseURL+FilesystemMoveProcedure,
			connect.WithSchema(filesystemMethods.ByName("Move")),
			connect.WithClientOptions(opts...),
		),
		listDir: connect.NewClient[pb.ListDirRequest, pb.ListDirResponse](
			httpClient,
			baseURL+FilesystemListDirProcedure,
			connect.WithSchema(filesystemMethods.ByName("ListDir")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[pb.RemoveRequest, pb.RemoveResponse](
			httpClient,
			baseURL+FilesystemRemoveProcedure,
			connect.WithSchema(filesystemMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
		watchDir: connect.NewClient[pb.WatchDirRequest, pb.WatchDirResponse](
			httpClient,
			baseURL+FilesystemWatchDirProcedure,
			connect.WithSchema(filesystemMethods.ByName("WatchDir")),
			connect.WithClientOptions(opts...),
		),
		createWatcher: connect.NewClient[pb.CreateWatcherRequest, pb.CreateWatcherResponse](
			httpClient,
			baseURL+FilesystemCreateWatcherProcedure,
			connect.WithSchema(filesystemMethods.ByName("CreateWatcher")),
			connect.WithClientOptions(opts...),
		),
		getWatcherEvents: connect.NewClient[pb.GetWatcherEventsRequest, pb.GetWatcherEventsResponse](
			httpClient,
			baseURL+FilesystemGetWatcherEventsProcedure,
			connect.WithSchema(filesystemMethods.ByName("GetWatcherEvents")),
			connect.WithClientOptions(opts...),
		),
		removeWatcher: connect.NewClient[pb.RemoveWatcherRequest, pb.RemoveWatcherResponse](
			httpClient,
			baseURL+FilesystemRemoveWatcherProcedure,
			connect.WithSchema(filesystemMethods.ByName("RemoveWatcher")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filesystemClient implements FilesystemClient.
type filesystemClient struct {
	stat             *connect.Client[pb.StatRequest, pb.StatResponse]
	makeDir          *connect.Client[pb.MakeDirRequest, pb.MakeDirResponse]
	move             *connect.Client[pb.MoveRequest, pb.MoveResponse]
	listDir          *connect.Client[pb.ListDirRequest, pb.ListDirResponse]
	remove           *connect.Client[pb.RemoveRequest, pb.RemoveResponse]
	watchDir         *connect.Client[pb.WatchDirRequest, pb.WatchDirResponse]
	createWatcher    *connect.Client[pb.CreateWatcherRequest, pb.CreateWatcherResponse]
	getWatcherEvents *connect.Client[pb.GetWatcherEventsRequest, pb.GetWatcherEventsResponse]
	removeWatcher    *connect.Client[pb.RemoveWatcherRequest, pb.RemoveWatcherResponse]
}

// Stat calls sandboxagent.Filesystem.Stat.
func (c *filesystemClient) Stat(ctx context.Context, req *connect.Request[pb.StatRequest]) (*connect.Response[pb.StatResponse], error) {
	return c.stat.CallUnary(ctx, req)
}

// MakeDir calls sandboxagent.Filesystem.MakeDir.
func (c *filesystemClient) MakeDir(ctx context.Context, req *connect.Request[pb.MakeDirRequest]) (*connect.Response[pb.MakeDirResponse], error) {
	return c.makeDir.CallUnary(ctx, req)
}

// Move calls sandboxagent.Filesystem.Move.
func (c *filesystemClient) Move(ctx context.Context, req *connect.Request[pb.MoveRequest]) (*connect.Response[pb.MoveResponse], error) {
	return c.move.CallUnary(ctx, req)
}

// ListDir calls sandboxagent.Filesystem.ListDir.
func (c *filesystemClient) ListDir(ctx context.Context, req *connect.Request[pb.ListDirRequest]) (*connect.Response[pb.ListDirResponse], error) {
	return c.listDir.CallUnary(ctx, req)
}

// Remove calls sandboxagent.Filesystem.Remove.
func (c *filesystemClient) Remove(ctx context.Context, req *connect.Request[pb.RemoveRequest]) (*connect.Response[pb.RemoveResponse], error) {
	return c.remove.CallUnary(ctx, req)
}

// WatchDir calls sandboxagent.Filesystem.WatchDir.
func (c *filesystemClient) WatchDir(ctx context.Context, req *connect.Request[pb.WatchDirRequest]) (*connect.ServerStreamForClient[pb.WatchDirResponse], error) {
	return c.watchDir.CallServerStream(ctx, req)
}

// CreateWatcher calls sandboxagent.Filesystem.CreateWatcher.
func (c *filesystemClient) CreateWatcher(ctx context.Context, req *connect.Request[pb.CreateWatcherRequest]) (*connect.Response[pb.CreateWatcherResponse], error) {
	return c.createWatcher.CallUnary(ctx, req)
}

// GetWatcherEvents calls sandboxagent.Filesystem.GetWatcherEvents.
func (c *filesystemClient) GetWatcherEvents(ctx context.Context, req *connect.Request[pb.GetWatcherEventsRequest]) (*connect.Response[pb.GetWatcherEventsResponse], error) {
	return c.getWatcherEvents.CallUnary(ctx, req)
}

// RemoveWatcher calls sandboxagent.Filesystem.RemoveWatcher.
func (c *filesystemClient) RemoveWatcher(ctx context.Context, req *connect.Request[pb.RemoveWatcherRequest]) (*connect.Response[pb.RemoveWatcherResponse], error) {
	return c.removeWatcher.CallUnary(ctx, req)
}

// FilesystemHandler is an implementation of the sandboxagent.Filesystem service.
type FilesystemHandler interface {
	Stat(context.Context, *connect.Request[pb.StatRequest]) (*connect.Response[pb.StatResponse], error)
	MakeDir(context.Context, *connect.Request[pb.MakeDirRequest]) (*connect.Response[pb.MakeDirResponse], error)
	Move(context.Context, *connect.Request[pb.MoveRequest]) (*connect.Response[pb.MoveResponse], error)
	ListDir(context.Context, *connect.Request[pb.ListDirRequest]) (*connect.Response[pb.ListDirResponse], error)
	Remove(context.Context, *connect.Request[pb.RemoveRequest]) (*connect.Response[pb.RemoveResponse], error)
	WatchDir(context.Context, *connect.Request[pb.WatchDirRequest], *connect.ServerStream[pb.WatchDirResponse]) error
	// Non-streaming versions of WatchDir
	CreateWatcher(context.Context, *connect.Request[pb.CreateWatcherRequest]) (*connect.Response[pb.CreateWatcherResponse], error)
	GetWatcherEvents(context.Context, *connect.Request[pb.GetWatcherEventsRequest]) (*connect.Response[pb.GetWatcherEventsResponse], error)
	RemoveWatcher(context.Context, *connect.Request[pb.RemoveWatcherRequest]) (*connect.Response[pb.RemoveWatcherResponse], error)
}

// NewFilesystemHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilesystemHandler(svc FilesystemHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filesystemMethods := pb.File_proto_api_proto.Services().ByName("Filesystem").Methods()
	filesystemStatHandler := connect.NewUnaryHandler(
		FilesystemStatProcedure,
		svc.Stat,
		connect.WithSchema(filesystemMethods.ByName("Stat")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemMakeDirHandler := connect.NewUnaryHandler(
		FilesystemMakeDirProcedure,
		svc.MakeDir,
		connect.WithSchema(filesystemMethods.ByName("MakeDir")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemMoveHandler := connect.NewUnaryHandler(
		FilesystemMoveProcedure,
		svc.Move,
		connect.WithSchema(filesystemMethods.ByName("Move")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemListDirHandler := connect.NewUnaryHandler(
		FilesystemListDirProcedure,
		svc.ListDir,
		connect.WithSchema(filesystemMethods.ByName("ListDir")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRemoveHandler := connect.NewUnaryHandler(
		FilesystemRemoveProcedure,
		svc.Remove,
		connect.WithSchema(filesystemMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemWatchDirHandler := connect.NewServerStreamHandler(
		FilesystemWatchDirProcedure,
		svc.WatchDir,
		connect.WithSchema(filesystemMethods.ByName("WatchDir")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemCreateWatcherHandler := connect.NewUnaryHandler(
		FilesystemCreateWatcherProcedure,
		svc.CreateWatcher,
		connect.WithSchema(filesystemMethods.ByName("CreateWatcher")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemGetWatcherEventsHandler := connect.NewUnaryHandler(
		FilesystemGetWatcherEventsProcedure,
		svc.GetWatcherEvents,
		connect.WithSchema(filesystemMethods.ByName("GetWatcherEvents")),
		connect.WithHandlerOptions(opts...),
	)
	filesystemRemoveWatcherHandler := connect.NewUnaryHandler(
		FilesystemRemoveWatcherProcedure,
		svc.RemoveWatcher,
		connect.WithSchema(filesystemMethods.ByName("RemoveWatcher")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandboxagent.Filesystem/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilesystemStatProcedure:
			filesystemStatHandler.ServeHTTP(w, r)
		case FilesystemMakeDirProcedure:
			filesystemMakeDirHandler.ServeHTTP(w, r)
		case FilesystemMoveProcedure:
			filesystemMoveHandler.ServeHTTP(w, r)
		case FilesystemListDirProcedure:
			filesystemListDirHandler.ServeHTTP(w, r)
		case FilesystemRemoveProcedure:
			filesystemRemoveHandler.ServeHTTP(w, r)
		case FilesystemWatchDirProcedure:
			filesystemWatchDirHandler.ServeHTTP(w, r)
		case FilesystemCreateWatcherProcedure:
			filesystemCreateWatcherHandler.ServeHTTP(w, r)
		case FilesystemGetWatcherEventsProcedure:
			filesystemGetWatcherEventsHandler.ServeHTTP(w, r)
		case FilesystemRemoveWatcherProcedure:
			filesystemRemoveWatcherHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilesystemHandler returns CodeUnimplemented from all methods.
type UnimplementedFilesystemHandler struct{}

func (UnimplementedFilesystemHandler) Stat(context.Context, *connect.Request[pb.StatRequest]) (*connect.Response[pb.StatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.Stat is not implemented"))
}

func (UnimplementedFilesystemHandler) MakeDir(context.Context, *connect.Request[pb.MakeDirRequest]) (*connect.Response[pb.MakeDirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.MakeDir is not implemented"))
}

func (UnimplementedFilesystemHandler) Move(context.Context, *connect.Request[pb.MoveRequest]) (*connect.Response[pb.MoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.Move is not implemented"))
}

func (UnimplementedFilesystemHandler) ListDir(context.Context, *connect.Request[pb.ListDirRequest]) (*connect.Response[pb.ListDirResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.ListDir is not implemented"))
}

func (UnimplementedFilesystemHandler) Remove(context.Context, *connect.Request[pb.RemoveRequest]) (*connect.Response[pb.RemoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.Remove is not implemented"))
}

func (UnimplementedFilesystemHandler) WatchDir(context.Context, *connect.Request[pb.WatchDirRequest], *connect.ServerStream[pb.WatchDirResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.WatchDir is not implemented"))
}

func (UnimplementedFilesystemHandler) CreateWatcher(context.Context, *connect.Request[pb.CreateWatcherRequest]) (*connect.Response[pb.CreateWatcherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.CreateWatcher is not implemented"))
}

func (UnimplementedFilesystemHandler) GetWatcherEvents(context.Context, *connect.Request[pb.GetWatcherEventsRequest]) (*connect.Response[pb.GetWatcherEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.GetWatcherEvents is not implemented"))
}

func (UnimplementedFilesystemHandler) RemoveWatcher(context.Context, *connect.Request[pb.RemoveWatcherRequest]) (*connect.Response[pb.RemoveWatcherResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Filesystem.RemoveWatcher is not implemented"))
}

// ProcessClient is a client for the sandboxagent.Process service.
type ProcessClient interface {
	List(context.Context, *connect.Request[pb.ListRequest]) (*connect.Response[pb.ListResponse], error)
	Connect(context.Context, *connect.Request[pb.ConnectRequest]) (*connect.ServerStreamForClient[pb.ConnectResponse], error)
	Start(context.Context, *connect.Request[pb.StartRequest]) (*connect.ServerStreamForClient[pb.StartResponse], error)
	Update(context.Context, *connect.Request[pb.UpdateRequest]) (*connect.Response[pb.UpdateResponse], error)
	// Client input stream ensures ordering of messages
	StreamInput(context.Context) *connect.ClientStreamForClient[pb.StreamInputRequest, pb.StreamInputResponse]
	SendInput(context.Context, *connect.Request[pb.SendInputRequest]) (*connect.Response[pb.SendInputResponse], error)
	SendSignal(context.Context, *connect.Request[pb.SendSignalRequest]) (*connect.Response[pb.SendSignalResponse], error)
}

// NewProcessClient constructs a client for the sandboxagent.Process service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProcessClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProcessClient {
	baseURL = strings.TrimRight(baseURL, "/")
	processMethods := pb.File_proto_api_proto.Services().ByName("Process").Methods()
	return &processClient{
		list: connect.NewClient[pb.ListRequest, pb.ListResponse](
			httpClient,
			baseURL+ProcessListProcedure,
			connect.WithSchema(processMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		connect: connect.NewClient[pb.ConnectRequest, pb.ConnectResponse](
			httpClient,
			baseURL+ProcessConnectProcedure,
			connect.WithSchema(processMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[pb.StartRequest, pb.StartResponse](
			httpClient,
			baseURL+ProcessStartProcedure,
			connect.WithSchema(processMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[pb.UpdateRequest, pb.UpdateResponse](
			httpClient,
			baseURL+ProcessUpdateProcedure,
			connect.WithSchema(processMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		streamInput: connect.NewClient[pb.StreamInputRequest, pb.StreamInputResponse](
			httpClient,
			baseURL+ProcessStreamInputProcedure,
			connect.WithSchema(processMethods.ByName("StreamInput")),
			connect.WithClientOptions(opts...),
		),
		sendInput: connect.NewClient[pb.SendInputRequest, pb.SendInputResponse](
			httpClient,
			baseURL+ProcessSendInputProcedure,
			connect.WithSchema(processMethods.ByName("SendInput")),
			connect.WithClientOptions(opts...),
		),
		sendSignal: connect.NewClient[pb.SendSignalRequest, pb.SendSignalResponse](
			httpClient,
			baseURL+ProcessSendSignalProcedure,
			connect.WithSchema(processMethods.ByName("SendSignal")),
			connect.WithClientOptions(opts...),
		),
	}
}

// processClient implements ProcessClient.
type processClient struct {
	list        *connect.Client[pb.ListRequest, pb.ListResponse]
	connect     *connect.Client[pb.ConnectRequest, pb.ConnectResponse]
	start       *connect.Client[pb.StartRequest, pb.StartResponse]
	update      *connect.Client[pb.UpdateRequest, pb.UpdateResponse]
	streamInput *connect.Client[pb.StreamInputRequest, pb.StreamInputResponse]
	sendInput   *connect.Client[pb.SendInputRequest, pb.SendInputResponse]
	sendSignal  *connect.Client[pb.SendSignalRequest, pb.SendSignalResponse]
}

// List calls sandboxagent.Process.List.
func (c *processClient) List(ctx context.Context, req *connect.Request[pb.ListRequest]) (*connect.Response[pb.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Connect calls sandboxagent.Process.Connect.
func (c *processClient) Connect(ctx context.Context, req *connect.Request[pb.ConnectRequest]) (*connect.ServerStreamForClient[pb.ConnectResponse], error) {
	return c.connect.CallServerStream(ctx, req)
}

// Start calls sandboxagent.Process.Start.
func (c *processClient) Start(ctx context.Context, req *connect.Request[pb.StartRequest]) (*connect.ServerStreamForClient[pb.StartResponse], error) {
	return c.start.CallServerStream(ctx, req)
}

// Update calls sandboxagent.Process.Update.
func (c *processClient) Update(ctx context.Context, req *connect.Request[pb.UpdateRequest]) (*connect.Response[pb.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// StreamInput calls sandboxagent.Process.StreamInput.
func (c *processClient) StreamInput(ctx context.Context) *connect.ClientStreamForClient[pb.StreamInputRequest, pb.StreamInputResponse] {
	return c.streamInput.CallClientStream(ctx)
}

// SendInput calls sandboxagent.Process.SendInput.
func (c *processClient) SendInput(ctx context.Context, req *connect.Request[pb.SendInputRequest]) (*connect.Response[pb.SendInputResponse], error) {
	return c.sendInput.CallUnary(ctx, req)
}

// SendSignal calls sandboxagent.Process.SendSignal.
func (c *processClient) SendSignal(ctx context.Context, req *connect.Request[pb.SendSignalRequest]) (*connect.Response[pb.SendSignalResponse], error) {
	return c.sendSignal.CallUnary(ctx, req)
}

// ProcessHandler is an implementation of the sandboxagent.Process service.
type ProcessHandler interface {
	List(context.Context, *connect.Request[pb.ListRequest]) (*connect.Response[pb.ListResponse], error)
	Connect(context.Context, *connect.Request[pb.ConnectRequest], *connect.ServerStream[pb.ConnectResponse]) error
	Start(context.Context, *connect.Request[pb.StartRequest], *connect.ServerStream[pb.StartResponse]) error
	Update(context.Context, *connect.Request[pb.UpdateRequest]) (*connect.Response[pb.UpdateResponse], error)
	// Client input stream ensures ordering of messages
	StreamInput(context.Context, *connect.ClientStream[pb.StreamInputRequest]) (*connect.Response[pb.StreamInputResponse], error)
	SendInput(context.Context, *connect.Request[pb.SendInputRequest]) (*connect.Response[pb.SendInputResponse], error)
	SendSignal(context.Context, *connect.Request[pb.SendSignalRequest]) (*connect.Response[pb.SendSignalResponse], error)
}

// NewProcessHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProcessHandler(svc ProcessHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	processMethods := pb.File_proto_api_proto.Services().ByName("Process").Methods()
	processListHandler := connect.NewUnaryHandler(
		ProcessListProcedure,
		svc.List,
		connect.WithSchema(processMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	processConnectHandler := connect.NewServerStreamHandler(
		ProcessConnectProcedure,
		svc.Connect,
		connect.WithSchema(processMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	processStartHandler := connect.NewServerStreamHandler(
		ProcessStartProcedure,
		svc.Start,
		connect.WithSchema(processMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	processUpdateHandler := connect.NewUnaryHandler(
		ProcessUpdateProcedure,
		svc.Update,
		connect.WithSchema(processMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	processStreamInputHandler := connect.NewClientStreamHandler(
		ProcessStreamInputProcedure,
		svc.StreamInput,
		connect.WithSchema(processMethods.ByName("StreamInput")),
		connect.WithHandlerOptions(opts...),
	)
	processSendInputHandler := connect.NewUnaryHandler(
		ProcessSendInputProcedure,
		svc.SendInput,
		connect.WithSchema(processMethods.ByName("SendInput")),
		connect.WithHandlerOptions(opts...),
	)
	processSendSignalHandler := connect.NewUnaryHandler(
		ProcessSendSignalProcedure,
		svc.SendSignal,
		connect.WithSchema(processMethods.ByName("SendSignal")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandboxagent.Process/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProcessListProcedure:
			processListHandler.ServeHTTP(w, r)
		case ProcessConnectProcedure:
			processConnectHandler.ServeHTTP(w, r)
		case ProcessStartProcedure:
			processStartHandler.ServeHTTP(w, r)
		case ProcessUpdateProcedure:
			processUpdateHandler.ServeHTTP(w, r)
		case ProcessStreamInputProcedure:
			processStreamInputHandler.ServeHTTP(w, r)
		case ProcessSendInputProcedure:
			processSendInputHandler.ServeHTTP(w, r)
		case ProcessSendSignalProcedure:
			processSendSignalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProcessHandler returns CodeUnimplemented from all methods.
type UnimplementedProcessHandler struct{}

func (UnimplementedProcessHandler) List(context.Context, *connect.Request[pb.ListRequest]) (*connect.Response[pb.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.List is not implemented"))
}

func (UnimplementedProcessHandler) Connect(context.Context, *connect.Request[pb.ConnectRequest], *connect.ServerStream[pb.ConnectResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.Connect is not implemented"))
}

func (UnimplementedProcessHandler) Start(context.Context, *connect.Request[pb.StartRequest], *connect.ServerStream[pb.StartResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.Start is not implemented"))
}

func (UnimplementedProcessHandler) Update(context.Context, *connect.Request[pb.UpdateRequest]) (*connect.Response[pb.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.Update is not implemented"))
}

func (UnimplementedProcessHandler) StreamInput(context.Context, *connect.ClientStream[pb.StreamInputRequest]) (*connect.Response[pb.StreamInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.StreamInput is not implemented"))
}

func (UnimplementedProcessHandler) SendInput(context.Context, *connect.Request[pb.SendInputRequest]) (*connect.Response[pb.SendInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.SendInput is not implemented"))
}

func (UnimplementedProcessHandler) SendSignal(context.Context, *connect.Request[pb.SendSignalRequest]) (*connect.Response[pb.SendSignalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.Process.SendSignal is not implemented"))
}

// ExecutionServiceClient is a client for the sandboxagent.ExecutionService service.
type ExecutionServiceClient interface {
	// 执行代码接口 (HTTP POST /execute)
	Execute(context.Context, *connect.Request[pb.ExecuteRequest]) (*connect.ServerStreamForClient[pb.ExecuteResponse], error)
}

// NewExecutionServiceClient constructs a client for the sandboxagent.ExecutionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewExecutionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ExecutionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	executionServiceMethods := pb.File_proto_api_proto.Services().ByName("ExecutionService").Methods()
	return &executionServiceClient{
		execute: connect.NewClient[pb.ExecuteRequest, pb.ExecuteResponse](
			httpClient,
			baseURL+ExecutionServiceExecuteProcedure,
			connect.WithSchema(executionServiceMethods.ByName("Execute")),
			connect.WithClientOptions(opts...),
		),
	}
}

// executionServiceClient implements ExecutionServiceClient.
type executionServiceClient struct {
	execute *connect.Client[pb.ExecuteRequest, pb.ExecuteResponse]
}

// Execute calls sandboxagent.ExecutionService.Execute.
func (c *executionServiceClient) Execute(ctx context.Context, req *connect.Request[pb.ExecuteRequest]) (*connect.ServerStreamForClient[pb.ExecuteResponse], error) {
	return c.execute.CallServerStream(ctx, req)
}

// ExecutionServiceHandler is an implementation of the sandboxagent.ExecutionService service.
type ExecutionServiceHandler interface {
	// 执行代码接口 (HTTP POST /execute)
	Execute(context.Context, *connect.Request[pb.ExecuteRequest], *connect.ServerStream[pb.ExecuteResponse]) error
}

// NewExecutionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewExecutionServiceHandler(svc ExecutionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	executionServiceMethods := pb.File_proto_api_proto.Services().ByName("ExecutionService").Methods()
	executionServiceExecuteHandler := connect.NewServerStreamHandler(
		ExecutionServiceExecuteProcedure,
		svc.Execute,
		connect.WithSchema(executionServiceMethods.ByName("Execute")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandboxagent.ExecutionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ExecutionServiceExecuteProcedure:
			executionServiceExecuteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedExecutionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedExecutionServiceHandler struct{}

func (UnimplementedExecutionServiceHandler) Execute(context.Context, *connect.Request[pb.ExecuteRequest], *connect.ServerStream[pb.ExecuteResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.ExecutionService.Execute is not implemented"))
}

// ContextServiceClient is a client for the sandboxagent.ContextService service.
type ContextServiceClient interface {
	// 创建执行上下文 (HTTP POST /contexts)
	CreateContext(context.Context, *connect.Request[pb.CreateContextRequest]) (*connect.Response[pb.Context], error)
	// 销毁执行上下文 (HTTP DELETE /contexts/{id})
	DestroyContext(context.Context, *connect.Request[pb.DestroyContextRequest]) (*connect.Response[pb.DestroyContextResponse], error)
}

// NewContextServiceClient constructs a client for the sandboxagent.ContextService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewContextServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ContextServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	contextServiceMethods := pb.File_proto_api_proto.Services().ByName("ContextService").Methods()
	return &contextServiceClient{
		createContext: connect.NewClient[pb.CreateContextRequest, pb.Context](
			httpClient,
			baseURL+ContextServiceCreateContextProcedure,
			connect.WithSchema(contextServiceMethods.ByName("CreateContext")),
			connect.WithClientOptions(opts...),
		),
		destroyContext: connect.NewClient[pb.DestroyContextRequest, pb.DestroyContextResponse](
			httpClient,
			baseURL+ContextServiceDestroyContextProcedure,
			connect.WithSchema(contextServiceMethods.ByName("DestroyContext")),
			connect.WithClientOptions(opts...),
		),
	}
}

// contextServiceClient implements ContextServiceClient.
type contextServiceClient struct {
	createContext  *connect.Client[pb.CreateContextRequest, pb.Context]
	destroyContext *connect.Client[pb.DestroyContextRequest, pb.DestroyContextResponse]
}

// CreateContext calls sandboxagent.ContextService.CreateContext.
func (c *contextServiceClient) CreateContext(ctx context.Context, req *connect.Request[pb.CreateContextRequest]) (*connect.Response[pb.Context], error) {
	return c.createContext.CallUnary(ctx, req)
}

// DestroyContext calls sandboxagent.ContextService.DestroyContext.
func (c *contextServiceClient) DestroyContext(ctx context.Context, req *connect.Request[pb.DestroyContextRequest]) (*connect.Response[pb.DestroyContextResponse], error) {
	return c.destroyContext.CallUnary(ctx, req)
}

// ContextServiceHandler is an implementation of the sandboxagent.ContextService service.
type ContextServiceHandler interface {
	// 创建执行上下文 (HTTP POST /contexts)
	CreateContext(context.Context, *connect.Request[pb.CreateContextRequest]) (*connect.Response[pb.Context], error)
	// 销毁执行上下文 (HTTP DELETE /contexts/{id})
	DestroyContext(context.Context, *connect.Request[pb.DestroyContextRequest]) (*connect.Response[pb.DestroyContextResponse], error)
}

// NewContextServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewContextServiceHandler(svc ContextServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	contextServiceMethods := pb.File_proto_api_proto.Services().ByName("ContextService").Methods()
	contextServiceCreateContextHandler := connect.NewUnaryHandler(
		ContextServiceCreateContextProcedure,
		svc.CreateContext,
		connect.WithSchema(contextServiceMethods.ByName("CreateContext")),
		connect.WithHandlerOptions(opts...),
	)
	contextServiceDestroyContextHandler := connect.NewUnaryHandler(
		ContextServiceDestroyContextProcedure,
		svc.DestroyContext,
		connect.WithSchema(contextServiceMethods.ByName("DestroyContext")),
		connect.WithHandlerOptions(opts...),
	)
	return "/sandboxagent.ContextService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ContextServiceCreateContextProcedure:
			contextServiceCreateContextHandler.ServeHTTP(w, r)
		case ContextServiceDestroyContextProcedure:
			contextServiceDestroyContextHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedContextServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedContextServiceHandler struct{}

func (UnimplementedContextServiceHandler) CreateContext(context.Context, *connect.Request[pb.CreateContextRequest]) (*connect.Response[pb.Context], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.ContextService.CreateContext is not implemented"))
}

func (UnimplementedContextServiceHandler) DestroyContext(context.Context, *connect.Request[pb.DestroyContextRequest]) (*connect.Response[pb.DestroyContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("sandboxagent.ContextService.DestroyContext is not implemented"))
}
